kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
spec:
  repo: "https://github.com/kubealex/k8s-mediaserver-helm"
  paths:
  - k8s-mediaserver
values:
  general:
    storage:
      customVolume: true
      volumes:
        hostPath:
          path: "F:\"